export default [
			{'name': '北京',
	            'luckynum':0},
	        {'name': '重庆',
	            'luckynum':0},
	        {'name': '上海',
	            'luckynum':0},
	        {'name': '天津',
	            'luckynum':0},
	        {'name': '长春',
	            'luckynum':0},
	        {'name': '长沙',
	            'luckynum':0},
	        {'name': '常州',
	            'luckynum':0},
	        {'name': '成都',
	            'luckynum':0},
	        {'name': '大连',
	            'luckynum':0},
	        {'name': '东莞',
	            'luckynum':0},
	        {'name': '佛山',
	            'luckynum':0},
	        {'name': '福州',
	            'luckynum':0},
	        {'name': '广州',
	            'luckynum':0},
	        {'name': '贵阳',
	            'luckynum':0},
	        {'name': '哈尔',
	            'luckynum':0},
	        {'name': '海口',
	            'luckynum':0},
	        {'name': '邯郸',
	            'luckynum':0},
	        {'name': '杭州',
	            'luckynum':0},
	        {'name': '合肥',
	            'luckynum':0},
	        {'name': '惠州',
	            'luckynum':0},
	        {'name': '焦作',
	            'luckynum':0},
	        {'name': '嘉兴',
	            'luckynum':0}
        ]
    
